spring:
  application:
    name: dndbookingbot

telegram:
  bot:
    token: ${BOT_TOKEN}

google:
  sheets:
    spreadsheet-id: ${GOOGLE_SPREADSHEET_ID}
    credentials-path: classpath:google/service-account.json